name: build
on:
  push:
    branches: [ main ]
    paths: 
      - 'offersku.json'
jobs:
  createIssue:
    env:
      GH_TOKEN: ${{secrets.GITHUB_TOKEN}}
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      name: Check out code
    - name: handle-list
      run: |
        cat .github/ISSUE_TEMPLATE/create_offersku.md > template.md
        deleteRow=$(grep -n "\-\-\-" template.md | cut -d ":" -f 1 | sed -n '2p')
        for ((index=0;index<$deleteRow;index++));do
          sed -i "${index}d" template.md
        done
        cat template.md
