name: build
on:
  push:
    branches: [ main ]
    paths: 
      - 'offersku.json'
jobs:
  createIssue:
    env:
      GH_TOKEN: ${{secrets.GITHUB_TOKEN}}
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      name: Check out code
    - name: handle-list
      run: |
        deleteRow=$(grep -n "---"  str.txt | cut -d ":" -f 1 | sed -n '2p')
        cat sed -i '1,'$deleteRow'd' .github/ISSUE_TEMPLATE/create_offersku.md > template.md
        cat template.md
