name: build
on:
  workflow_dispatch
#   push:
#     branches: [ main ]
#     paths: 
#       - 'offersku.json'
jobs:
  createIssue:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      name: Check out code
    - name: handle-list
      run: |
        milestone=$(cat offersku.json | jq '.mailstone')
        echo $milestone
        jq "[.task[] | {appname:.appname,version:.version[],distribution:.distribution[],platform:.platform[],os:.os[],assignees:.assignees}]" offersku.json
        cat offersku.json
#        gh issue create --project "Roadmap" --assignee monalisa --title "I found a bug" --body "Nothing works" --body-file <file> --milestone <name>
          
        
