name: build
on:
  push:
    branches: [ main ]
#     paths: 
#       - 'offersku.json'
jobs:
  createIssue:
    env:
      GH_TOKEN: ${{secrets.GITHUB_TOKEN}}
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      name: Check out code
    - name: handle-list
      run: |
        milestone=$(cat offersku.json | jq '.mailstone')
        list=$(jq "[.task[] | {appname:.appname,version:.version[],distribution:.distribution[],platform:.platform[],os:.os[],assignees:.assignees}]" offersku.json)
        length=$(echo $list | jq '.|length')
        for ((index=0;index<$length;index++));do
          appname=$(echo $list | jq ".[$index].appname")
          version=$(echo $list | jq ".[$index].version")
          distribution=$(echo $list | jq ".[$index].distribution")
          platform=$(echo $list | jq ".[$index].platform")
          os=$(echo $list | jq ".[$index].os")
          assignees=$(echo $list | jq ".[$index].assignees")
          gh issue create --assignee $assignees --title "$appname$version $distribution on $os on $platform" --body-file .github/ISSUE_TEMPLATE/create_offersku.md --milestone $milestone
        done



        
