name: build
on:
  push:
    branches: [ main ]
    paths: 
      - 'offersku.json'
jobs:
  createIssue:
    env:
      GH_TOKEN: ${{secrets.GITHUB_TOKEN}}
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      name: Check out code
    - name: handle-list
      run: |
        milestone=$(cat offersku.json | jq '.mailstone')
        allMilestones=$(curl \
          -H "Accept: application/vnd.github+json" \
          -H "Authorization: Bearer ${{github.token}}"\
          -H "X-GitHub-Api-Version: 2022-11-28" \
          https://api.github.com/repos/${{github.repository_owner}}/manufacture/milestones | jq  '.[] | .title')
        
        createFlag="true"
        for item in $allMilestones;do
          if [[ $item == $milestone ]];then
            createFlag="false"
            echo "milestone exist"
            break
          fi 
        done
        if [[ $createFlag == "true" ]];then
          echo "create new milestone"
          curl \
            -X POST \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer ${{github.token}}"\
            -H "X-GitHub-Api-Version: 2022-11-28" \
            https://api.github.com/repos/${{github.repository_owner}}/manufacture/milestones \
            -d '{"title":'$milestone',"state":"open"}'
        fi
        
        length=$(echo $list | jq '.|length')  
        list=$(jq "[.task[] | {appname:.appname,version:.version[],distribution:.distribution[],platform:.platform[],os:.os[],assignees:.assignees}]" offersku.json)
        length=$(echo $list | jq '.|length')
        for ((index=0;index<$length;index++));do
          appname=$(echo $list | jq -r ".[$index].appname")
          version=$(echo $list | jq -r ".[$index].version")
          distribution=$(echo $list | jq -r ".[$index].distribution")
          platform=$(echo $list | jq -r ".[$index].platform")
          os=$(echo $list | jq -r ".[$index].os")
          assignee=$(echo $list | jq -r ".[$index].assignees")
          stone=$(echo $milestone | sed 's/\"//g')
          url=$(gh issue create --assignee $assignee --title "$appname$version $distribution on $os on $platform" --body-file .github/ISSUE_TEMPLATE/create_offersku.md --milestone $stone)
          echo "$url" | awk -F "/" '{print $NF}'
        done
