name: build
on:
  push:
    branches: [ main ]
#     paths: 
#       - 'offersku.json'
jobs:
  createIssue:
    env:
      GH_TOKEN: ${{secrets.GITHUB_TOKEN}}
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      name: Check out code
    - name: handle-list
      run: |
        milestone=$(cat offersku.json | jq '.mailstone' | sed 's/\"//g')
        
        allMilestones=$(curl \
          -H "Accept: application/vnd.github+json" \
          -H "Authorization: Bearer ${{secrets.GIHUB_TOKEN}}"\
          -H "X-GitHub-Api-Version: 2022-11-28" \
          https://api.github.com/repos/${{github.repository_owner}}/manufacture/milestones | jq ".title" | sed 's/\"//g')
          
        cat $allMilestones  
        
        length=$(echo $list | jq '.|length')  
        for ((index=0;index<$length;index++));do
        
        list=$(jq "[.task[] | {appname:.appname,version:.version[],distribution:.distribution[],platform:.platform[],os:.os[],assignees:.assignees}]" offersku.json)
        length=$(echo $list | jq '.|length')
        for ((index=0;index<$length;index++));do
          appname=$(echo $list | jq ".[$index].appname" | sed 's/\"//g')
          version=$(echo $list | jq ".[$index].version" | sed 's/\"//g')
          distribution=$(echo $list | jq ".[$index].distribution" | sed 's/\"//g')
          platform=$(echo $list | jq ".[$index].platform" | sed 's/\"//g')
          os=$(echo $list | jq ".[$index].os" | sed 's/\"//g')
          assignees=$(echo $list | jq ".[$index].assignees" | sed 's/\"//g')
          gh issue create --assignee $assignees --title "$appname$version $distribution on $os on $platform" --body-file .github/ISSUE_TEMPLATE/create_offersku.md --milestone $milestone
        done



        
