name: build
on:
  push:
    branches: [ main ]
    paths: 
      - 'offersku.json'
jobs:
  createIssue:
    env:
      GH_TOKEN: ${{secrets.GITHUB_TOKEN}}
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      name: Check out code
    - name: handle-list
      run: |
        project_id=$(curl --request POST \
          --url https://api.github.com/graphql \
          --header 'Authorization: Bearer ${{ secrets.ACCESS_PROJECT }}' \
          --data '{"query":"query{user(login: \"${{github.repository_owner}}\") {projectV2(number: 2){id}}}"}' | jq -r .data.user.projectV2.id)
        field_id=$(curl --request POST \
          --url https://api.github.com/graphql \
          --header 'Authorization: Bearer ${{ secrets.ACCESS_PROJECT }}' \
          --data '{"query":"query{ node(id: \"'$project_id'\") { ... on ProjectV2 { fields(first: 20) { nodes { ... on ProjectV2Field { id name } ... on ProjectV2IterationField { id name configuration { iterations { startDate id }}} ... on ProjectV2SingleSelectField { id name options { id name }}}}}}}"}')
        status_id=$(echo $field_id | jq -r '.data.node.fields.nodes[2].id'
        produce_id=$(echo $field_id | jq -r '.data.node.fields.nodes[2].options[1].id'
        
